services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8080:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:17beta2-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - my_db:/var/lib/postgresql/data
volumes:
  my_db:
  my_media:
